site_name: AGL Playbook (ALPHA)
repo_url: https://github.com/batgne/agileDocs/

theme:
    name: readthedocs

nav:
    - Welcome: index.md
    - Start Here: start.md
    - References:
      - Videos we like: 'videos.md'
      - Articles we like: 'articles.md' 
    - About: about.md

